remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Configuración básica
title: "AITOR RODRÍGUEZ WEBLOG"
url: "https://aitorrm.github.io"
baseurl: ""

# Configuración regional
locale: "es-ES"

# Configuración del Favicon
favicon: "/images/favicon/favicon.ico"

# Configuración de iconos
header:
  # El tema usa este campo para el icono de la cabecera (opcional)
  logo: "/images/favicon/favicon-32x32.png"

# Plugins necesarios
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Directorio de páginas
include:
  - _pages
  - _data

# Configuración de enlaces permanentes (Permalinks)
permalink: /:categories/:title/

# Ajuste para que las páginas en _pages se procesen bien
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      comments: true # Esto activa la caja de comentarios Disqus
      read_time: true
      related: true
      entries_layout: grid
      author_profile: true
  - scope:
      path: "_pages"
    values:
      layout: "single"

# Desactivar basura que da error
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache

# Desactivar la búsqueda de archivos locales que ya no existen
include_cache:
  enabled: false

# Navigation
navigation:
  - main

# Paginación (para que no salgan todos los posts en una sola página)
paginate: 5
paginate_path: "/page:num/"

# Configuración del home
home:
  type: posts

author:
  name   : "Aitor Rodríguez"
  avatar : "/images/aitor_profile.jpg"
  bio    : "Ingeniero Informático. Agile Delivery Leader con backgroung técnico."
  location: "España"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aitorrm/"

# Configuración de Comentarios
comments:
  provider: "disqus"
  disqus:
    shortname: "aitorrodriguezweblog" # Sustituye esto por tu nombre real en Disqus

# Configuración de posts relacionados
related_limit: 4
