remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Configuración básica
title: "AITOR RODRÍGUEZ WEBLOG"
url: "https://aitorrm.github.io"
baseurl: ""

# Plugins necesarios
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

# Esto fuerza a tus posts antiguos a usar el layout nuevo
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      author_profile: true

# Desactivar basura que da error
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
