remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Configuración básica
title: "AITOR RODRÍGUEZ WEBLOG"
url: "https://aitorrm.github.io"
baseurl: ""

# Plugins necesarios
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Directorio de páginas
include:
  - _pages

# Configuración de enlaces permanentes (Permalinks)
permalink: /:categories/:title/

# Ajuste para que las páginas en _pages se procesen bien
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
  - scope:
      path: "_pages"
    values:
      layout: "single"

# Desactivar basura que da error
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache

# Navigation
navigation:
  - main

# Paginación (para que no salgan todos los posts en una sola página)
paginate: 7
paginate_path: "/page:num/"

# Configuración del home
home:
  type: posts
